{
  LOG.info("Aborting because of " + StringUtils.stringifyException(t));
  try {
    downlink.abort();
    downlink.flush();
  }
 catch (  IOException e) {
  }
  try {
    handler.waitForFinish();
  }
 catch (  Throwable ignored) {
    process.destroy();
  }
  IOException wrapper=new IOException("pipe child exception");
  wrapper.initCause(t);
  throw wrapper;
}
