{
  Exception ex=new Exception("test exception");
  SerializedExceptionPBImpl pb=new SerializedExceptionPBImpl();
  try {
    pb.deSerialize();
    Assert.fail("deSerialze should throw YarnRuntimeException");
  }
 catch (  YarnRuntimeException e) {
    Assert.assertEquals(ClassNotFoundException.class,e.getCause().getClass());
  }
  pb.init(ex);
  Assert.assertEquals(ex.toString(),pb.deSerialize().toString());
}
