{
  return new Callable<Void>(){
    @Override public Void call() throws Exception {
      try {
        buf.limit(length);
        actualReadFromBlock(reader.blockReader,buf);
        return null;
      }
 catch (      ChecksumException e) {
        LOG.warn("Found Checksum error for " + reader.block + " from "+ reader.source+ " at "+ e.getPos());
        addCorruptedBlock(reader.block,reader.source,corruptionMap);
        throw e;
      }
catch (      IOException e) {
        LOG.info(e.getMessage());
        throw e;
      }
    }
  }
;
}
