{
  this.stopped=true;
  interrupt();
  try {
    join(5000);
  }
 catch (  InterruptedException ie) {
    LOG.warn("Got interrupted while joining " + getName(),ie);
  }
}
