{
  Throwable innerException=e.getCause();
  while (innerException != null && !(innerException instanceof StorageException)) {
    innerException=innerException.getCause();
  }
  return innerException;
}
