{
  try {
    assertExceptionContains("",new BrokenException());
  }
 catch (  AssertionError e) {
    if (!e.toString().contains(E_NULL_THROWABLE_STRING)) {
      throw e;
    }
  }
}
