{
  try {
    assertExceptionContains("",null);
  }
 catch (  AssertionError e) {
    if (!e.toString().contains(E_NULL_THROWABLE)) {
      throw e;
    }
  }
}
