{
  try {
    File f=checkHadoopHomeInner(path);
    fail("Expected an exception with the text `" + expectedText + "`"+ " -but got the path "+ f);
    return null;
  }
 catch (  FileNotFoundException ex) {
    assertExContains(ex,expectedText);
    return ex;
  }
}
