{
  Exception latestException;
  int counter=0;
  do {
    try {
      return doExecute(arguments);
    }
 catch (    Exception exception) {
      LOG.error("Failure in Retriable command: " + description,exception);
      latestException=exception;
    }
    counter++;
  }
 while (retryPolicy.shouldRetry(latestException,counter,0,true).equals(RetryPolicy.RetryAction.RETRY));
  throw new IOException("Couldn't run retriable-command: " + description,latestException);
}
