{
  throw new YarnException("test exception");
}
