{
  return failoverOnNetworkException(TRY_ONCE_THEN_FAIL,maxFailovers);
}
