{
  if (failsOnceRemoteExceptionInvocationCount++ == 0) {
    throw new RemoteException(IOException.class.getName(),"test exception for failsOnceWithRemoteException");
  }
}
