{
  boolean getException=false;
  try {
    namenode.getBlocks(DFSTestUtil.getLocalDatanodeInfo(),2);
  }
 catch (  RemoteException e) {
    getException=true;
    assertTrue(e.getClassName().contains("HadoopIllegalArgumentException"));
  }
  assertTrue(getException);
}
