{
  try {
    new CallQueueManager<FakeCall>(queueClass,exceptionSchedulerClass,false,10,"",new Configuration());
    fail();
  }
 catch (  RuntimeException re) {
    assertTrue(re.getCause() instanceof IllegalArgumentException);
    assertEquals("Exception caused by scheduler constructor.!!",re.getCause().getMessage());
  }
}
